version: '3'

services:
  traefik:
    container_name: pickup-traefik
    image: traefik:latest
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
      - "18080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.docker/traefik/traefik.toml:/etc/traefik/traefik.toml:ro
    labels:
      - "traefik.frontend.rule=Host:srv.pickup.localhost"
      - "traefik.port=8080"

  php:
    container_name: pickup-php
    build: .docker/php
    depends_on:
      - db
    volumes:
      - ./api:/home/pickup/api:rw
      - ./api/var:/home/pickup/api/var:rw,cached
    labels:
      - "traefik.frontend.rule=Host:php.pickup.localhost"

  front:
    container_name: pickup-front
    image: node:lts-alpine
    working_dir: /home/pickup/front
    volumes:
      - ./front:/home/pickup/front
    ports:
      - "8080:8080"
    labels:
      - "traefik.frontend.rule=Host:pickup.localhost"
      - "traefik.port=8080"
    command: ["yarn", "serve"]

  admin:
    container_name: pickup-admin
    image: node:lts-alpine
    working_dir: /home/pickup/admin
    volumes:
      - ./admin:/home/pickup/admin
    ports:
      - "3000:3000"
    labels:
      - "traefik.frontend.rule=Host:admin.pickup.localhost"
      - "traefik.port=3000"
    command: ["yarn", "start"]

  web:
    container_name: pickup-web
    image: nginx:1.15-alpine
    depends_on:
      - php
    volumes:
      - ./api/public:/home/pickup/api/public:ro
      - ./.docker/nginx:/etc/nginx/conf.d:ro
    labels:
      - "traefik.frontend.rule=Host:api.pickup.localhost"
      - "traefik.port=80"

  db:
    container_name: pickup-db
    image: postgres:10-alpine
    ports:
      - "55432:5432"
    volumes:
      - database:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=pickup
      - POSTGRES_USER=pickup
      - POSTGRES_PASSWORD=pickup
    labels:
      - "traefik.frontend.rule=Host:db.pickup.localhost"

volumes:
  database: {}

